import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'data/models/task_model.dart';
import 'data/models/search_history_model.dart';
import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Hive.initFlutter();
  
  // Register Adapters
  // Note: These Adapters (TaskAdapter, SearchHistoryAdapter) are generated by build_runner.
  // Ensure you run 'dart run build_runner build' before running the app.
  Hive.registerAdapter(TaskAdapter());
  Hive.registerAdapter(SearchHistoryAdapter());

  runApp(const ProviderScope(child: FocusMeApp()));
}
